-- Create accounts table
CREATE TABLE IF NOT EXISTS public.accounts (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Asset', 'Liability', 'Equity', 'Income', 'Expense')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create journal_entries table
CREATE TABLE IF NOT EXISTS public.journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    debit_account TEXT REFERENCES public.accounts(code) ON DELETE RESTRICT,
    credit_account TEXT REFERENCES public.accounts(code) ON DELETE RESTRICT,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allow full access for authenticated users for now)
CREATE POLICY "Enable all for users based on email" ON public.accounts
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Enable all for users based on email" ON public.journal_entries
    FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.accounts;
ALTER PUBLICATION supabase_realtime ADD TABLE public.journal_entries;

-- Seed Initial Chart of Accounts (COA)
INSERT INTO public.accounts (code, name, type) VALUES
    ('101', 'Kas', 'Asset'),
    ('102', 'Bank', 'Asset'),
    ('103', 'Piutang Usaha', 'Asset'),
    ('104', 'Persediaan', 'Asset'),
    ('201', 'Hutang Usaha', 'Liability'),
    ('301', 'Modal', 'Equity'),
    ('302', 'Prive', 'Equity'),
    ('401', 'Pendapatan Penjualan', 'Income'),
    ('402', 'Pendapatan Lain-lain', 'Income'),
    ('501', 'Beban Pembelian', 'Expense'),
    ('502', 'Beban Gaji', 'Expense'),
    ('503', 'Beban Sewa', 'Expense'),
    ('504', 'Beban Listrik & Air', 'Expense'),
    ('505', 'Beban Lain-lain', 'Expense')
ON CONFLICT (code) DO NOTHING;

-- Seed Initial Transactions (Optional/Demo)
INSERT INTO public.journal_entries (date, description, debit_account, credit_account, amount) VALUES
    ('2023-10-01', 'Setoran Modal Awal', '102', '301', 100000000),
    ('2023-10-02', 'Pembelian Perlengkapan', '505', '101', 500000),
    ('2023-10-03', 'Penjualan Tunai', '101', '401', 2500000),
    ('2023-10-05', 'Bayar Listrik', '504', '102', 1200000)
ON CONFLICT DO NOTHING;
