-- Assessment Criteria Table
CREATE TABLE IF NOT EXISTS public.assessment_criteria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    icon TEXT DEFAULT 'Star', -- lucide icon name
    branch_id UUID REFERENCES public.branches(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.assessment_criteria ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Enable all access for authenticated users" ON public.assessment_criteria
    FOR ALL USING (auth.role() = 'authenticated');

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.assessment_criteria;

-- Seed default criteria if needed
INSERT INTO public.assessment_criteria (label, icon) VALUES 
('Kedisiplinan', 'ClipboardCheck'),
('Komunikasi', 'Users'),
('Kerjasama Tim', 'Users'),
('Sikap & Etika', 'Star'),
('Produktivitas', 'TrendingUp');
