-- Create attendance_logs table
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    employee_name TEXT NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    check_in TEXT, -- Storing as text 'HH:MM' to match UI format, or TIME
    check_out TEXT,
    status TEXT, -- 'Present', 'Late', 'Off Day Work'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Enable all for users based on email" ON public.attendance_logs
    FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.attendance_logs;
