-- Create branches table
CREATE TABLE IF NOT EXISTS public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    phone TEXT,
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Enable all for users based on email" ON public.branches
    FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.branches;

-- Seed Initial Data
INSERT INTO public.branches (name, address, phone) VALUES
    ('Winny Cafe Pusat', 'Jl. Ahmad Yani No. 1, Jakarta', '021-1234567'),
    ('Winny Cafe Cabang 02', 'Jl. Sudirman No. 45, Bandung', '022-7654321')
ON CONFLICT DO NOTHING;
