-- Create Cashier Sessions Table
CREATE TABLE IF NOT EXISTS public.cashier_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id TEXT NOT NULL, 
    user_id UUID REFERENCES auth.users(id), 
    employee_name TEXT, 
    opened_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    
    starting_cash NUMERIC DEFAULT 0,
    
    cash_sales NUMERIC DEFAULT 0,
    card_sales NUMERIC DEFAULT 0,
    qris_sales NUMERIC DEFAULT 0,
    total_sales NUMERIC DEFAULT 0,
    
    expected_cash NUMERIC DEFAULT 0, 
    actual_cash NUMERIC DEFAULT 0,   
    difference NUMERIC DEFAULT 0,    
    
    status TEXT DEFAULT 'Open' CHECK (status IN ('Open', 'Closed')),
    notes TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.cashier_sessions ENABLE ROW LEVEL SECURITY;

-- Policies
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Enable read/write for authenticated users" ON public.cashier_sessions;
    CREATE POLICY "Enable read/write for authenticated users" ON public.cashier_sessions
        FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
        
EXCEPTION
    WHEN undefined_table THEN
        NULL;
END $$;

-- Add Settings Columns
ALTER TABLE public.store_settings 
ADD COLUMN IF NOT EXISTS require_starting_cash BOOLEAN DEFAULT TRUE;

ALTER TABLE public.store_settings 
ADD COLUMN IF NOT EXISTS require_blind_close BOOLEAN DEFAULT FALSE;

ALTER TABLE public.store_settings 
ADD COLUMN IF NOT EXISTS auto_open_drawer BOOLEAN DEFAULT FALSE;

ALTER TABLE public.store_settings 
ADD COLUMN IF NOT EXISTS quick_cash_amounts JSONB DEFAULT '[10000, 20000, 50000, 100000]';
