-- Create Promos Table
create table if not exists public.promos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  type text not null check (type in ('manual', 'automatic')),
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  value numeric not null,
  min_spend numeric default 0,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  is_active boolean default true,
  branch_id bigint references public.branches(id) on delete cascade
);

-- Create Promo Products Table (Many-to-Many)
create table if not exists public.promo_products (
  id bigint generated by default as identity primary key,
  promo_id bigint references public.promos(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete cascade not null,
  unique(promo_id, product_id)
);

-- Enable RLS
alter table public.promos enable row level security;
alter table public.promo_products enable row level security;

-- Create generic read policy
create policy "Enable read access for all users" on public.promos for select using (true);
create policy "Enable read access for all users" on public.promo_products for select using (true);

-- Create generic write policy (auth only)
create policy "Enable write access for auth users" on public.promos for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Enable write access for auth users" on public.promo_products for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Enable realtime (Commented out because some Supabase instances have FOR ALL TABLES enabled)
-- alter publication supabase_realtime add table public.promos;
-- alter publication supabase_realtime add table public.promo_products;
