-- Create Master Data Tables
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text
);

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  abbreviation text not null
);

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text
);

-- Create Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  code text not null,
  name text not null,
  category text, -- simplified for now, or use FK generic
  brand text,    -- simplified for now
  unit text,     -- simplified for now
  price numeric default 0,
  cost numeric default 0,
  stock numeric default 0,
  image_url text
);

-- Create Recipe Table (Many-to-Many: Product <-> Ingredient)
create table if not exists public.product_recipes (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade not null,
  ingredient_id bigint, -- References inventory, assumes inventory table exists or loosely coupled
  amount numeric not null
);

-- Create Addons Table (One-to-Many: Product -> Addons)
create table if not exists public.product_addons (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade not null,
  name text not null,
  price numeric default 0
);

-- Enable RLS
alter table public.categories enable row level security;
alter table public.units enable row level security;
alter table public.brands enable row level security;
alter table public.products enable row level security;
alter table public.product_recipes enable row level security;
alter table public.product_addons enable row level security;

-- Create generic read policy
create policy "Enable read access for all users" on public.categories for select using (true);
create policy "Enable read access for all users" on public.units for select using (true);
create policy "Enable read access for all users" on public.brands for select using (true);
create policy "Enable read access for all users" on public.products for select using (true);
create policy "Enable read access for all users" on public.product_recipes for select using (true);
create policy "Enable read access for all users" on public.product_addons for select using (true);

-- Create generic write policy (auth only)
create policy "Enable write access for auth users" on public.categories for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Enable write access for auth users" on public.units for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Enable write access for auth users" on public.brands for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Enable write access for auth users" on public.products for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Enable write access for auth users" on public.product_recipes for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Enable write access for auth users" on public.product_addons for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Enable realtime
alter publication supabase_realtime add table public.categories;
alter publication supabase_realtime add table public.units;
alter publication supabase_realtime add table public.brands;
alter publication supabase_realtime add table public.products;
