-- Create Purchases Table
create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  purchase_no text not null,
  supplier_name text not null,
  date date not null,
  total_amount numeric default 0,
  items_count integer default 0,
  status text default 'Pending' -- Pending, Completed, Returned
);

-- Create Purchase Returns Table
create table if not exists public.purchase_returns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  return_no text not null,
  purchase_no text not null, -- Reference to purchases.purchase_no (loose coupling for now or strict FK if preferred)
  date date not null,
  reason text,
  status text default 'Pending' -- Pending, Processed
);

-- Enable RLS
alter table public.purchases enable row level security;
alter table public.purchase_returns enable row level security;

-- Create generic read policy
create policy "Enable read access for all users" on public.purchases for select using (true);
create policy "Enable read access for all users" on public.purchase_returns for select using (true);

-- Create generic write policy (auth only)
create policy "Enable write access for auth users" on public.purchases for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Enable write access for auth users" on public.purchase_returns for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Enable realtime
alter publication supabase_realtime add table public.purchases;
alter publication supabase_realtime add table public.purchase_returns;
