-- Create Leave Requests Table
CREATE TABLE IF NOT EXISTS public.leave_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint REFERENCES public.employees(id) ON DELETE CASCADE,
    employee_name text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    reason text,
    type text NOT NULL CHECK (type IN ('Cuti Tahunan', 'Sakit', 'Izin', 'Lainnya')),
    status text NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;

-- Policy: Allow unrestricted access for now (to avoid strict RLS issues during development)
-- In production, this should be stricter (e.g., only own requests or admin)
CREATE POLICY "Enable all access for all users" ON public.leave_requests
    FOR ALL USING (true) WITH CHECK (true);

-- Grant permissions
GRANT ALL ON public.leave_requests TO anon, authenticated, service_role;
