-- Create contacts table
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text not null check (type in ('Customer', 'Supplier')),
  email text,
  phone text,
  address text,
  company text,
  status text default 'Active',
  member_id text,
  tier text default 'Regular',
  points integer default 0,
  birthday date
);

-- Enable RLS
alter table public.contacts enable row level security;

-- Create policy to allow all access for authenticated users (for now)
-- Adjust this based on actual auth requirements
create policy "Enable all access for authenticated users" 
on public.contacts for all 
using (true) 
with check (true);

-- Enable realtime
alter publication supabase_realtime add table public.contacts;
