-- Create contacts table for Customers and Suppliers
CREATE TABLE IF NOT EXISTS public.contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    type text NOT NULL CHECK (type IN ('Customer', 'Supplier')),
    email text,
    phone text,
    address text,
    company text,
    status text DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    member_id text,
    tier text CHECK (tier IN ('Regular', 'Silver', 'Gold', 'Platinum')),
    points numeric DEFAULT 0,
    birthday date
);

-- Enable RLS
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allow full access for now for simplicity, can be restricted later)
CREATE POLICY "Enable read access for all users" ON public.contacts FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.contacts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.contacts FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.contacts FOR DELETE USING (true);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_contacts_phone ON public.contacts(phone);
CREATE INDEX IF NOT EXISTS idx_contacts_member_id ON public.contacts(member_id);
