-- Create Sales Table
create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_no text not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  total_amount numeric default 0,
  payment_method text,
  status text default 'Completed',
  branch_id integer,
  waiter_name text,
  customer_id bigint -- Optional link to contacts
);

-- Create Sale Items Table
create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete cascade not null,
  product_id bigint references public.products(id), -- Optional strict FK
  product_name text not null, -- Snapshot name
  quantity numeric default 1,
  price numeric default 0,
  cost numeric default 0 -- Snapshot cost for reporting
);

-- Create Sales Returns Table
create table if not exists public.sales_returns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  return_no text not null,
  sale_id bigint references public.sales(id),
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  reason text,
  refund_amount numeric default 0,
  status text default 'Processed'
);

-- Enable RLS
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.sales_returns enable row level security;

-- Create generic read policy
create policy "Enable read access for all users" on public.sales for select using (true);
create policy "Enable read access for all users" on public.sale_items for select using (true);
create policy "Enable read access for all users" on public.sales_returns for select using (true);

-- Create generic write policy (auth only)
create policy "Enable write access for auth users" on public.sales for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Enable write access for auth users" on public.sale_items for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Enable write access for auth users" on public.sales_returns for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Enable realtime
alter publication supabase_realtime add table public.sales;
alter publication supabase_realtime add table public.sale_items;
alter publication supabase_realtime add table public.sales_returns;
