-- Create departments table
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create employees table
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    department TEXT NOT NULL, -- Storing name directly for simplicity in UI, can be FK if strict
    email TEXT,
    phone TEXT,
    join_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'On Leave', 'Terminated')),
    off_days JSONB DEFAULT '[]'::jsonb, -- Array of integers [0,1,2...]
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allow full access for authenticated users for now)
CREATE POLICY "Enable all for users based on email" ON public.departments
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Enable all for users based on email" ON public.employees
    FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.departments;
ALTER PUBLICATION supabase_realtime ADD TABLE public.employees;

-- Seed Initial Departments
INSERT INTO public.departments (name) VALUES
    ('Operations'),
    ('Kitchen'),
    ('Bar'),
    ('Finance'),
    ('HR')
ON CONFLICT (name) DO NOTHING;

-- Seed Initial Employees
INSERT INTO public.employees (name, position, department, status, join_date, off_days) VALUES
    ('Andi S.', 'Waitress', 'Operations', 'Active', '2025-01-01', '[1]'),
    ('Budi R.', 'Barista', 'Bar', 'Active', '2025-02-15', '[2]')
ON CONFLICT DO NOTHING;
