-- Employee Assessments Table
CREATE TABLE IF NOT EXISTS public.employee_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    period TEXT NOT NULL, -- e.g. "Maret 2026"
    scores JSONB NOT NULL DEFAULT '{}'::jsonb, -- map of criteria -> score
    total_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    average_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    feedback TEXT,
    reviewer_name TEXT NOT NULL,
    branch_id UUID REFERENCES public.branches(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.employee_assessments ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Enable all access for authenticated users" ON public.employee_assessments
    FOR ALL USING (auth.role() = 'authenticated');

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.employee_assessments;
