-- ENSURE INGREDIENTS & INVENTORY TABLES EXIST

-- 1. Ingredients Table
CREATE TABLE IF NOT EXISTS public.ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    unit TEXT NOT NULL,
    category TEXT NOT NULL,
    current_stock NUMERIC DEFAULT 0,
    min_stock NUMERIC DEFAULT 0,
    cost_per_unit NUMERIC DEFAULT 0,
    last_updated DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Stock Movements Table
CREATE TABLE IF NOT EXISTS public.stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT REFERENCES public.ingredients(id) ON DELETE CASCADE,
    ingredient_name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('IN', 'OUT', 'ADJUSTMENT')),
    quantity NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    reason TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    "user" TEXT DEFAULT 'System',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable RLS
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Permissive for development)
DROP POLICY IF EXISTS "Enable all access" ON public.ingredients;
CREATE POLICY "Enable all access" ON public.ingredients FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access" ON public.stock_movements;
CREATE POLICY "Enable all access" ON public.stock_movements FOR ALL USING (true) WITH CHECK (true);

-- 5. Realtime (Skipped because publication is already FOR ALL TABLES)
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.ingredients;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.stock_movements;

-- 6. Seed Data (So you have something to choose for Recipe)
INSERT INTO public.ingredients (name, unit, category, current_stock, min_stock, cost_per_unit) VALUES
    ('Kopi Arabika (Beans)', 'kg', 'Coffee', 10, 2, 120000),
    ('Gula Aren', 'Liter', 'Sweetener', 5, 1, 25000),
    ('Susu UHT', 'Liter', 'Dairy', 24, 5, 18000),
    ('Bubuk Cokelat', 'kg', 'Powder', 5, 1, 85000),
    ('Es Batu', 'kg', 'Other', 50, 10, 2000)
ON CONFLICT DO NOTHING;
