-- Create ingredients table
CREATE TABLE IF NOT EXISTS public.ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    unit TEXT NOT NULL,
    category TEXT NOT NULL,
    current_stock NUMERIC DEFAULT 0,
    min_stock NUMERIC DEFAULT 0,
    cost_per_unit NUMERIC DEFAULT 0,
    last_updated DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create stock_movements table
CREATE TABLE IF NOT EXISTS public.stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT REFERENCES public.ingredients(id) ON DELETE CASCADE,
    ingredient_name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('IN', 'OUT', 'ADJUSTMENT')),
    quantity NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    reason TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    "user" TEXT DEFAULT 'System',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Enable all for users based on email" ON public.ingredients
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Enable all for users based on email" ON public.stock_movements
    FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.ingredients;
ALTER PUBLICATION supabase_realtime ADD TABLE public.stock_movements;

-- Seed Initial Ingredients (Optional - matching dummy data for smooth transition)
INSERT INTO public.ingredients (name, unit, category, current_stock, min_stock, cost_per_unit, last_updated) VALUES
    ('Kopi Arabika (Beans)', 'kg', 'Coffee', 25.5, 5, 150000, CURRENT_DATE),
    ('Susu Fresh Milk', 'Liter', 'Dairy', 12, 10, 18000, CURRENT_DATE),
    ('Gula Aren Cair', 'Liter', 'Sweetener', 3.5, 5, 25000, CURRENT_DATE),
    ('Bubuk Cokelat Premium', 'kg', 'Other', 8, 2, 120000, CURRENT_DATE)
ON CONFLICT DO NOTHING;
