-- MASTER DB SETUP SCRIPT
-- Run this script in the Supabase SQL Editor to create all necessary tables.

-- 1. Master Data Tables (No dependencies)
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text not null check (type in ('Customer', 'Supplier')),
  email text,
  phone text,
  address text,
  company text,
  status text default 'Active',
  member_id text,
  tier text default 'Regular',
  points integer default 0,
  birthday date
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text
);

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  abbreviation text not null
);

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text
);

CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Product related tables
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  code text not null,
  name text not null,
  category text, 
  brand text,    
  unit text,     
  price numeric default 0,
  cost numeric default 0,
  stock numeric default 0,
  image_url text
);

create table if not exists public.product_recipes (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade not null,
  ingredient_id bigint, 
  amount numeric not null
);

create table if not exists public.product_addons (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade not null,
  name text not null,
  price numeric default 0
);

-- 3. Purchasing tables
create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  purchase_no text not null,
  supplier_name text not null,
  date date not null,
  total_amount numeric default 0,
  items_count integer default 0,
  status text default 'Pending' 
);

create table if not exists public.purchase_returns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  return_no text not null,
  purchase_no text not null, 
  date date not null,
  reason text,
  status text default 'Pending' 
);

-- 4. Sales tables
create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_no text not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  total_amount numeric default 0,
  payment_method text,
  status text default 'Completed',
  branch_id integer,
  waiter_name text,
  customer_id bigint 
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete cascade not null,
  product_id bigint references public.products(id), 
  product_name text not null, 
  quantity numeric default 1,
  price numeric default 0,
  cost numeric default 0 
);

create table if not exists public.sales_returns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  return_no text not null,
  sale_id bigint references public.sales(id),
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  reason text,
  refund_amount numeric default 0,
  status text default 'Processed'
);

-- 5. Employee & HR Tables
CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    department TEXT NOT NULL, 
    email TEXT,
    phone TEXT,
    join_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'On Leave', 'Terminated')),
    off_days JSONB DEFAULT '[]'::jsonb, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    employee_name TEXT NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    check_in TEXT, 
    check_out TEXT,
    status TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.payrolls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    employee_name TEXT NOT NULL,
    position TEXT,
    period TEXT NOT NULL, 
    basic_salary NUMERIC DEFAULT 0,
    allowance NUMERIC DEFAULT 0,
    deduction NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Paid')),
    payment_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Accounting Tables
CREATE TABLE IF NOT EXISTS public.accounts (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Asset', 'Liability', 'Equity', 'Income', 'Expense')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    debit_account TEXT REFERENCES public.accounts(code) ON DELETE RESTRICT,
    credit_account TEXT REFERENCES public.accounts(code) ON DELETE RESTRICT,
    amount NUMERIC NOT NULL CHECK (amount > 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ENABLE RLS (Row Level Security) on ALL Tables
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payrolls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;


-- CREATE POLICIES (Assuming full access for authenticated users for internal tools)
-- Note: 'ON CONFLICT DO NOTHING' is used to avoid errors if policies already exist when re-running partially
DO $$
BEGIN
    -- Contacts
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'contacts' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.contacts FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Categories
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'categories' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.categories FOR ALL USING (true) WITH CHECK (true);
    END IF;
     -- Units
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'units' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.units FOR ALL USING (true) WITH CHECK (true);
    END IF;
     -- Brands
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'brands' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.brands FOR ALL USING (true) WITH CHECK (true);
    END IF;
     -- Departments
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'departments' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.departments FOR ALL USING (true) WITH CHECK (true);
    END IF;
     -- Products
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'products' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.products FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Product Recipes
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'product_recipes' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.product_recipes FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Product Addons
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'product_addons' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.product_addons FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Purchases
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'purchases' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.purchases FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Purchase Returns
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'purchase_returns' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.purchase_returns FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Sales
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'sales' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.sales FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Sale Items
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'sale_items' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.sale_items FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Sales Returns
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'sales_returns' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.sales_returns FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Employees
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'employees' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.employees FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Attendance
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'attendance_logs' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.attendance_logs FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Payrolls
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'payrolls' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.payrolls FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Accounts
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'accounts' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.accounts FOR ALL USING (true) WITH CHECK (true);
    END IF;
    -- Journal Entries
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'journal_entries' AND policyname = 'Enable all access') THEN
        CREATE POLICY "Enable all access" ON public.journal_entries FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;


-- ENABLE REALTIME
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime for all tables;
commit;
