-- Create payrolls table
CREATE TABLE IF NOT EXISTS public.payrolls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    employee_name TEXT NOT NULL,
    position TEXT,
    period TEXT NOT NULL, -- e.g., 'Januari 2026'
    basic_salary NUMERIC DEFAULT 0,
    allowance NUMERIC DEFAULT 0,
    deduction NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Paid')),
    payment_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.payrolls ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Enable all for users based on email" ON public.payrolls
    FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.payrolls;
