-- 1. Create payrolls table if not exists
CREATE TABLE IF NOT EXISTS public.payrolls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    employee_name TEXT NOT NULL,
    position TEXT,
    period TEXT NOT NULL, -- e.g., 'Januari 2026'
    basic_salary NUMERIC DEFAULT 0,
    allowance NUMERIC DEFAULT 0,
    deduction NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Paid')),
    payment_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Reset Policy (Safe for re-run)
ALTER TABLE public.payrolls ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for users based on email" ON public.payrolls;
CREATE POLICY "Enable all for users based on email" ON public.payrolls FOR ALL USING (true) WITH CHECK (true);

-- 3. NOTE: Realtime is already enabled for all tables, so no extra command needed.
