-- Create performance_adjustments table
CREATE TABLE IF NOT EXISTS public.performance_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE SET NULL,
    employee_name TEXT NOT NULL,
    amount DECIMAL DEFAULT 0,
    reason TEXT,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.performance_adjustments ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Enable all for everyone" ON public.performance_adjustments
    FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.performance_adjustments;
