-- Performance Evaluations Schema
BEGIN;

-- 1. Performance Evaluations (Header)
CREATE TABLE IF NOT EXISTS public.performance_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    evaluation_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_score NUMERIC NOT NULL DEFAULT 0,
    base_salary NUMERIC NOT NULL DEFAULT 0, -- [NEW]
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Performance Evaluation Details
CREATE TABLE IF NOT EXISTS public.performance_evaluation_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT REFERENCES public.performance_evaluations(id) ON DELETE CASCADE,
    indicator_id BIGINT REFERENCES public.performance_indicators(id) ON DELETE SET NULL,
    indicator_label TEXT NOT NULL,
    score NUMERIC NOT NULL DEFAULT 0,
    weight NUMERIC NOT NULL DEFAULT 0,
    total NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.performance_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.performance_evaluation_details ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.performance_evaluations;
CREATE POLICY "Enable all access for authenticated users" ON public.performance_evaluations
    FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.performance_evaluation_details;
CREATE POLICY "Enable all access for authenticated users" ON public.performance_evaluation_details
    FOR ALL USING (auth.role() = 'authenticated');

COMMIT;
