-- Create performance_rules table
CREATE TABLE IF NOT EXISTS public.performance_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    commission_percent NUMERIC DEFAULT 1.5,
    attendance_bonus NUMERIC DEFAULT 10000,
    late_penalty NUMERIC DEFAULT 25000,
    complaint_penalty NUMERIC DEFAULT 50000,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Create employee_complaints table
CREATE TABLE IF NOT EXISTS public.employee_complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    reason TEXT,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.performance_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_complaints ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable all for everyone" ON public.performance_rules FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for everyone" ON public.employee_complaints FOR ALL USING (true) WITH CHECK (true);

-- Seed initial rules for ID 1 (global default if no branch)
INSERT INTO public.performance_rules (id, commission_percent, attendance_bonus, late_penalty, complaint_penalty)
VALUES (1, 1.5, 10000, 25000, 50000)
ON CONFLICT (id) DO NOTHING;
