-- Master Performance Indicators Schema
BEGIN;

CREATE TABLE IF NOT EXISTS public.performance_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    weight NUMERIC NOT NULL DEFAULT 0,
    branch_id BIGINT REFERENCES public.branches(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.performance_indicators ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable all access for authenticated users" ON public.performance_indicators
    FOR ALL USING (auth.role() = 'authenticated');

-- Initial Seed Data
INSERT INTO public.performance_indicators (label, weight) VALUES 
('Kedisiplinan & Kehadiran', 20),
('Kualitas Pekerjaan', 20),
('Produktivitas & Efisiensi', 20),
('Sikap & Kerjasama Tim', 20),
('Inisiatif & Inovasi', 20);

COMMIT;
