-- Petty Cash Module Schema
-- Tracks daily opening and closing of funds per branch

-- 1. Petty Cash Sessions Table
CREATE TABLE IF NOT EXISTS petty_cash_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    branch_id UUID NOT NULL,
    opening_balance NUMERIC(15, 2) DEFAULT 0,
    expected_balance NUMERIC(15, 2) DEFAULT 0,
    actual_closing_balance NUMERIC(15, 2),
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID,
    closed_at TIMESTAMP WITH TIME ZONE,
    
    -- Ensure only one open session per branch per day (or just per branch at a time)
    UNIQUE(date, branch_id)
);

-- 2. Petty Cash Transactions Table
CREATE TABLE IF NOT EXISTS petty_cash_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES petty_cash_sessions(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('TOPUP', 'SPEND')),
    amount NUMERIC(15, 2) NOT NULL,
    description TEXT,
    reference_type TEXT, -- 'purchase', 'manual', 'opening'
    reference_id TEXT, -- purchase_no, journal_id, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Update active balance function
CREATE OR REPLACE FUNCTION update_petty_cash_expected_balance()
RETURNS TRIGGER AS $$
BEGIN
    -- 1. Handle DELETION or BEFORE UPDATE (Revert old data)
    IF (TG_OP = 'DELETE' OR TG_OP = 'UPDATE') THEN
        IF (OLD.type = 'TOPUP') THEN
            UPDATE petty_cash_sessions SET expected_balance = expected_balance - OLD.amount WHERE id = OLD.session_id;
        ELSE
            UPDATE petty_cash_sessions SET expected_balance = expected_balance + OLD.amount WHERE id = OLD.session_id;
        END IF;
    END IF;

    -- 2. Handle INSERTION or AFTER UPDATE (Apply new data)
    IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') THEN
        IF (NEW.type = 'TOPUP') THEN
            UPDATE petty_cash_sessions SET expected_balance = expected_balance + NEW.amount WHERE id = NEW.session_id;
        ELSE
            UPDATE petty_cash_sessions SET expected_balance = expected_balance - NEW.amount WHERE id = NEW.session_id;
        END IF;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_petty_cash_balance ON petty_cash_transactions;
CREATE TRIGGER trg_update_petty_cash_balance
AFTER INSERT OR DELETE OR UPDATE ON petty_cash_transactions
FOR EACH ROW EXECUTE FUNCTION update_petty_cash_expected_balance();

-- Add payment_method to purchases table if not exists
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='purchases' AND column_name='payment_method') THEN
        ALTER TABLE purchases ADD COLUMN payment_method TEXT DEFAULT 'Tunai';
    END IF;
END $$;
