-- Create shifts table
CREATE TABLE IF NOT EXISTS public.shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    color TEXT DEFAULT 'bg-blue-100 text-blue-700',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create shift_schedules table
CREATE TABLE IF NOT EXISTS public.shift_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    shift_id BIGINT REFERENCES public.shifts(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_schedules ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Enable all for users based on email" ON public.shifts
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Enable all for users based on email" ON public.shift_schedules
    FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.shifts;
ALTER PUBLICATION supabase_realtime ADD TABLE public.shift_schedules;

-- Seed Initial Shifts
INSERT INTO public.shifts (name, start_time, end_time, color) VALUES
    ('Pagi', '07:00', '15:00', 'bg-blue-100 text-blue-700'),
    ('Sore', '15:00', '23:00', 'bg-orange-100 text-orange-700'),
    ('Full Day', '08:00', '20:00', 'bg-purple-100 text-purple-700')
ON CONFLICT DO NOTHING;
