-- Create shifts table
CREATE TABLE IF NOT EXISTS public.shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    color TEXT DEFAULT 'bg-blue-100 text-blue-700',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure color column exists if table was already created earlier
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='shifts' AND column_name='color') THEN
        ALTER TABLE public.shifts ADD COLUMN color TEXT DEFAULT 'bg-blue-100 text-blue-700';
    END IF;
END $$;

-- Create shift_schedules table
CREATE TABLE IF NOT EXISTS public.shift_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES public.employees(id) ON DELETE CASCADE,
    employee_name TEXT NOT NULL,
    shift_id BIGINT REFERENCES public.shifts(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    custom_start_time TEXT,
    custom_end_time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure custom columns exist if table was already created earlier
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='shift_schedules' AND column_name='custom_start_time') THEN
        ALTER TABLE public.shift_schedules ADD COLUMN custom_start_time TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='shift_schedules' AND column_name='custom_end_time') THEN
        ALTER TABLE public.shift_schedules ADD COLUMN custom_end_time TEXT;
    END IF;
END $$;

-- Enable RLS
ALTER TABLE public.shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_schedules ENABLE ROW LEVEL SECURITY;

-- Create Policies
DROP POLICY IF EXISTS "Enable all for users based on email" ON public.shifts;
CREATE POLICY "Enable all for users based on email" ON public.shifts
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all for users based on email" ON public.shift_schedules;
CREATE POLICY "Enable all for users based on email" ON public.shift_schedules
    FOR ALL USING (true) WITH CHECK (true);

-- Enable Realtime (Optional: Only if NOT set to 'FOR ALL TABLES')
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.shifts;
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.shift_schedules;

-- Seed Initial Shifts
INSERT INTO public.shifts (name, start_time, end_time, color) VALUES
    ('Pagi', '07:00', '15:00', 'bg-blue-100 text-blue-700'),
    ('Sore', '15:00', '23:00', 'bg-orange-100 text-orange-700'),
    ('Full Day', '08:00', '20:00', 'bg-purple-100 text-purple-700')
ON CONFLICT DO NOTHING;
