-- Create roles table
create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  permissions jsonb default '[]'::jsonb
);

-- Enable RLS (Optional but recommended, though for now we might leave it open for simplicity if policies aren't set)
alter table public.roles enable row level security;

-- Create Policy: Allow authenticated users to read roles
create policy "Enable read access for all users" on public.roles
  for select using (auth.role() = 'authenticated');

-- Create Policy: Allow authenticated users (or specific admins) to insert/update/delete
-- For simplicity in this dev phase, allowing all authenticated users to edit roles.
-- In production, you'd restrict this to specific user IDs or role types.
create policy "Enable insert for authenticated users" on public.roles
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users" on public.roles
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users" on public.roles
  for delete using (auth.role() = 'authenticated');
