-- Create tables table
create table public.tables (
  id bigint generated by default as identity primary key,
  number text not null,
  capacity integer default 4,
  status text default 'Available', -- Available, Occupied, Reserved
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.tables enable row level security;

-- Create policies
create policy "Enable read access for all users" on public.tables for select using (true);
create policy "Enable insert for authenticated users only" on public.tables for insert with check (auth.role() = 'authenticated');
create policy "Enable update for authenticated users only" on public.tables for update using (auth.role() = 'authenticated');
create policy "Enable delete for authenticated users only" on public.tables for delete using (auth.role() = 'authenticated');

-- Insert default tables
insert into public.tables (number, capacity) values 
('T1', 4), ('T2', 4), ('T3', 4), ('T4', 2), ('T5', 6),
('T6', 4), ('T7', 4), ('T8', 2), ('T9', 8), ('T10', 4);
