-- Create table for WiFi vouchers
CREATE TABLE IF NOT EXISTS public.wifi_vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    is_used BOOLEAN DEFAULT FALSE,
    used_at TIMESTAMP WITH TIME ZONE,
    sale_id BIGINT REFERENCES public.sales(id),
    branch_id TEXT DEFAULT 'default',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_wifi_vouchers_unused ON public.wifi_vouchers(is_used) WHERE is_used = FALSE;

-- Enable RLS
ALTER TABLE public.wifi_vouchers ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable all for authenticated users" ON public.wifi_vouchers
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- Add setting to store_settings
ALTER TABLE public.store_settings 
ADD COLUMN IF NOT EXISTS enable_wifi_vouchers BOOLEAN DEFAULT FALSE;

ALTER TABLE public.store_settings 
ADD COLUMN IF NOT EXISTS wifi_voucher_notice TEXT DEFAULT 'Gunakan kode di bawah ini untuk akses WiFi';
