
-- Create history table for Recipe and HPP changes
CREATE TABLE IF NOT EXISTS recipe_hpp_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    product_name TEXT,
    old_cost DECIMAL(15,2),
    new_cost DECIMAL(15,2),
    recipe_snapshot JSONB,
    changed_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_recipe_hpp_history_product_id ON recipe_hpp_history(product_id);
CREATE INDEX IF NOT EXISTS idx_recipe_hpp_history_created_at ON recipe_hpp_history(created_at);
